/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/FullDoorAssembly.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/FullDoorAssembly.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="97-0477" geometry={nodes['97-0477'].geometry} material={materials['1.000000_1.000000_1.000000_0.000000_0.000000']} position={[-0.24, 3.198, 1.912]} rotation={[1.583, -0.002, -0.2]} />
        <mesh name="97-0760" geometry={nodes['97-0760'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.000000']} position={[-0.241, 3.197, 1.906]} rotation={[1.581, -0.002, -0.2]} />
        <group name="d000921930-000" position={[-0.033, 2.963, 1.906]} rotation={[0, 0, -Math.PI]}>
          <mesh name="mesh0_mesh002" geometry={nodes.mesh0_mesh002.geometry} material={materials['1.000000_1.000000_1.000000_0.000000_0.001']} />
          <mesh name="mesh0_mesh002_1" geometry={nodes.mesh0_mesh002_1.geometry} material={materials['0.000000_0.329412_1.000000_0.000000_0.000000']} />
        </group>
        <mesh name="97-0541tab" geometry={nodes['97-0541tab'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.002']} position={[-0.241, 3.198, 1.902]} rotation={[-3.116, -0.194, -3.132]} />
        <mesh name="98-0018" geometry={nodes['98-0018'].geometry} material={materials['1.000000_0.000000_1.000000_0.000000_0.000000']} position={[-0.033, 2.923, 1.922]} rotation={[-Math.PI, 0, 3.099]} />
        <mesh name="68-1392" geometry={nodes['68-1392'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.006']} position={[-0.012, 2.939, 1.914]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="Part_1" geometry={nodes.Part_1.geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.007']} position={[-0.244, 3.136, 1.844]} rotation={[0.001, 0, -Math.PI]} scale={[1, 1, 0.827]} />
        <mesh name="Part_1001" geometry={nodes.Part_1001.geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.008']} position={[-0.242, 3.231, 1.897]} rotation={[3.138, -0.2, 3.141]} />
        <mesh name="97-0425TAB" geometry={nodes['97-0425TAB'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.009']} position={[-0.254, 3.139, 1.902]} rotation={[-3.13, -0.244, -3.087]} scale={[1, 1.129, 0.999]} />
        <mesh name="68-1380" geometry={nodes['68-1380'].geometry} material={materials['1.000000_1.000000_1.000000_0.000000_0.002']} position={[-0.008, 2.963, 1.947]} rotation={[-Math.PI / 2, 0, 2.702]} />
        <mesh name="68-1392001" geometry={nodes['68-1392001'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.010']} position={[-0.02, 2.963, 1.942]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[1.57, 1, 1]} />
        <group name="01-4512" position={[-0.074, 2.986, 1.915]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="mesh0_mesh018" geometry={nodes.mesh0_mesh018.geometry} material={materials['1.000000_0.000000_1.000000_0.000000_0.001']} />
          <mesh name="mesh0_mesh018_1" geometry={nodes.mesh0_mesh018_1.geometry} material={materials['1.000000_0.329412_0.000000_0.000000_0.000000']} />
        </group>
        <mesh name="98-0028" geometry={nodes['98-0028'].geometry} material={materials['0.615686_0.639216_0.674510_0.000000_0.000000']} position={[-0.02, 2.979, 1.94]} rotation={[-1.285, 0.03, 0.061]} scale={[1, 1.246, 1.017]} />
        <mesh name="01-0008" geometry={nodes['01-0008'].geometry} material={materials['1.000000_0.658824_0.000000_0.000000_0.000000']} position={[-0.228, 3.103, 1.703]} rotation={[1.666, -1.477, 1.672]} />
        <mesh name="98-0011" geometry={nodes['98-0011'].geometry} material={materials['0.000000_0.658824_1.000000_0.000000_0.000000']} position={[-0.052, 2.923, 1.927]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
        <group name="68-1366_import" position={[-0.049, 3.003, 1.927]} rotation={[0.485, 1.548, 0.879]}>
          <mesh name="mesh0_mesh022" geometry={nodes.mesh0_mesh022.geometry} material={materials['0.400000_0.000000_0.400000_0.000000_0.000000']} />
          <mesh name="mesh0_mesh022_1" geometry={nodes.mesh0_mesh022_1.geometry} material={materials['1.000000_0.658824_0.000000_0.000000_0.001']} />
        </group>
        <mesh name="68-1365_TAB_tester_68-1367" geometry={nodes['68-1365_TAB_tester_68-1367'].geometry} material={materials['0.400000_0.000000_0.400000_0.000000_0.001']} position={[-0.049, 2.923, 1.927]} rotation={[3.101, -1.548, 1.429]} />
        <mesh name="97-0480" geometry={nodes['97-0480'].geometry} material={materials['0.776471_0.776471_0.819608_0.000000_0.000000']} position={[-0.241, 3.197, 1.904]} rotation={[-3.135, -0.195, -3.14]} />
        <mesh name="68-0548TAB" geometry={nodes['68-0548TAB'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.011']} position={[-0.398, 2.755, 1.833]} rotation={[1.555, 1.567, 0]} />
        <mesh name="68-0946_TAB_wiegand_68-0952_(1)" geometry={nodes['68-0946_TAB_wiegand_68-0952_(1)'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.012']} position={[0.085, 2.754, 1.814]} rotation={[1.572, -Math.PI / 2, 0]} />
        <mesh name="97-0557" geometry={nodes['97-0557'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.015']} position={[-0.241, 3.245, 1.9]} rotation={[0.007, 0.2, -0.001]} />
        <mesh name="01-1182" geometry={nodes['01-1182'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.016']} position={[-0.235, 3.183, 1.9]} rotation={[0, -1.358, -0.006]} />
        <mesh name="PP1793_MORTISE_82-0157" geometry={nodes['PP1793_MORTISE_82-0157'].geometry} material={materials['1.000000_1.000000_1.000000_0.000000_0.003']} position={[-0.239, 3.197, 1.919]} rotation={[-0.007, 0.2, -0.001]} />
        <mesh name="97-0355" geometry={nodes['97-0355'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.017']} position={[-0.241, 3.25, 1.9]} rotation={[-3.135, -0.209, -3.14]} />
        <mesh name="97-0571" geometry={nodes['97-0571'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.018']} position={[-0.241, 3.245, 1.902]} rotation={[0.007, 0.2, -0.001]} />
        <mesh name="68-1393" geometry={nodes['68-1393'].geometry} material={materials['1.000000_1.000000_1.000000_0.000000_0.004']} position={[-0.241, 3.198, 1.898]} rotation={[0.007, 0.2, -0.001]} />
        <mesh name="Part_1002" geometry={nodes.Part_1002.geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.019']} position={[-0.241, 3.244, 1.9]} rotation={[-3.135, -0.208, -3.14]} />
        <mesh name="98-0018001" geometry={nodes['98-0018001'].geometry} material={materials['1.000000_0.000000_1.000000_0.000000_0.002']} position={[-0.033, 3.003, 1.922]} rotation={[-Math.PI, 0, -3.135]} />
        <mesh name="98-0011001" geometry={nodes['98-0011001'].geometry} material={materials['0.000000_0.658824_1.000000_0.000000_0.001']} position={[-0.052, 3.003, 1.927]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
        <mesh name="68-1392002" geometry={nodes['68-1392002'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.020']} position={[-0.012, 2.987, 1.915]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="01-0005_retaining_ring" geometry={nodes['01-0005_retaining_ring'].geometry} material={nodes['01-0005_retaining_ring'].material} position={[-0.024, 2.914, 1.908]} rotation={[-3.142, -1.569, 0]} scale={-0.001} />
        <mesh name="68-1137_lift_arm" geometry={nodes['68-1137_lift_arm'].geometry} material={materials['Material.004']} position={[-0.026, 2.956, 1.915]} rotation={[-Math.PI, 0.13, -Math.PI]} scale={0.001} />
        <mesh name="01-0005_retaining_ring001" geometry={nodes['01-0005_retaining_ring001'].geometry} material={nodes['01-0005_retaining_ring001'].material} position={[-0.024, 2.994, 1.908]} rotation={[-3.142, -1.569, 0]} scale={-0.001} />
        <group name="01-4512001" position={[-0.008, 2.985, 1.946]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="mesh0_mesh040" geometry={nodes.mesh0_mesh040.geometry} material={materials['1.000000_0.000000_1.000000_0.000000_0.003']} />
          <mesh name="mesh0_mesh040_1" geometry={nodes.mesh0_mesh040_1.geometry} material={materials['1.000000_0.329412_0.000000_0.000000_0.001']} />
        </group>
        <mesh name="01-0011_Lock_Washer" geometry={nodes['01-0011_Lock_Washer'].geometry} material={nodes['01-0011_Lock_Washer'].material} position={[0.175, 2.778, 1.806]} rotation={[0, 0, Math.PI / 2]} scale={0.001} />
        <mesh name="01-3622_Strike_Screw" geometry={nodes['01-3622_Strike_Screw'].geometry} material={nodes['01-3622_Strike_Screw'].material} position={[0.165, 2.868, 1.499]} scale={0.001} />
        <mesh name="68-0406_8800_Cover" geometry={nodes['68-0406_8800_Cover'].geometry} material={materials['Material.009']} position={[0.042, 2.857, 1.906]} rotation={[-Math.PI, 0, -1.56]} scale={0.001} />
        <mesh name="68-0879_End_Cap" geometry={nodes['68-0879_End_Cap'].geometry} material={materials['Material.003']} position={[-0.657, 2.783, 1.682]} rotation={[3.128, 0, 1.566]} scale={0.001} />
        <mesh name="68-1434_End_Cap_Bracket" geometry={nodes['68-1434_End_Cap_Bracket'].geometry} material={materials.Material} position={[-0.811, 2.75, 1.667]} rotation={[-Math.PI, 0, -1.577]} scale={0.001} />
        <mesh name="68-3905_Cover_Screw" geometry={nodes['68-3905_Cover_Screw'].geometry} material={materials['Material.008']} position={[-0.009, 2.908, 1.911]} rotation={[-Math.PI, 0, -1.566]} scale={0.001} />
        <mesh name="97-0395_649_Strike" geometry={nodes['97-0395_649_Strike'].geometry} material={materials['Material.002']} position={[0.175, 2.886, 1.781]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
        <mesh name="01-2455_Bracket_Mounting_Screw" geometry={nodes['01-2455_Bracket_Mounting_Screw'].geometry} material={nodes['01-2455_Bracket_Mounting_Screw'].material} position={[-0.861, 2.8, 1.67]} rotation={[1.565, 0, 0]} scale={0.001} />
        <mesh name="01-2455_Bracket_Mounting_Screw001" geometry={nodes['01-2455_Bracket_Mounting_Screw001'].geometry} material={nodes['01-2455_Bracket_Mounting_Screw001'].material} position={[-0.861, 2.827, 1.67]} rotation={[1.565, 0, 0]} scale={0.001} />
        <mesh name="68-3905_Cover_Screw001" geometry={nodes['68-3905_Cover_Screw001'].geometry} material={materials['Material.007']} position={[-0.008, 3.011, 1.911]} rotation={[-Math.PI, 0, -1.566]} scale={0.001} />
        <mesh name="68-3905_Cover_Screw002" geometry={nodes['68-3905_Cover_Screw002'].geometry} material={materials['Material.006']} position={[-0.056, 3.019, 1.911]} rotation={[Math.PI, 0, 1.576]} scale={0.001} />
        <mesh name="68-3905_Cover_Screw003" geometry={nodes['68-3905_Cover_Screw003'].geometry} material={materials['Material.005']} position={[-0.057, 2.916, 1.911]} rotation={[Math.PI, 0, 1.576]} scale={0.001} />
        <mesh name="Part_1004" geometry={nodes.Part_1004.geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.001']} position={[-0.244, 3.155, 1.825]} rotation={[0.001, 0, -Math.PI]} scale={[1, 1, 0.827]} />
        <mesh name="13-1480TAB_Plug" geometry={nodes['13-1480TAB_Plug'].geometry} material={materials['Material.013']} position={[-0.247, 3.271, 1.906]} rotation={[1.576, 0, 0.043]} scale={0.001} />
        <mesh name="13-1038TAB_41_mortise_cyl" geometry={nodes['13-1038TAB_41_mortise_cyl'].geometry} material={nodes['13-1038TAB_41_mortise_cyl'].material} position={[-0.255, 3.268, 1.907]} rotation={[1.577, 0, 0.043]} scale={0.001} />
        <mesh name="14-0028TAB_(KEY)" geometry={nodes['14-0028TAB_(KEY)'].geometry} material={materials['Material.010']} position={[-0.236, 3.263, 1.956]} rotation={[Math.PI / 2, 0, -1.528]} scale={0.001} />
        <mesh name="01-1121_Cam_Screws" geometry={nodes['01-1121_Cam_Screws'].geometry} material={nodes['01-1121_Cam_Screws'].material} position={[-0.246, 3.277, 1.906]} rotation={[-Math.PI, -1.528, 3.135]} scale={0.001} />
        <mesh name="standard_cam" geometry={nodes.standard_cam.geometry} material={nodes.standard_cam.material} position={[-0.235, 3.272, 1.907]} rotation={[1.577, 0, -3.105]} scale={0.001} />
        <mesh name="97-0348_TAB_97-0350_Collar" geometry={nodes['97-0348_TAB_97-0350_Collar'].geometry} material={materials['Material.011']} position={[-0.224, 3.267, 1.916]} rotation={[-3.135, 0.049, 3.141]} scale={0.001} />
        <mesh name="Cyl_Cap" geometry={nodes.Cyl_Cap.geometry} material={materials['Material.012']} position={[-0.253, 3.268, 1.931]} rotation={[1.577, 0, 0.043]} scale={0.001} />
        <mesh name="13-0180_Cylinder_Nut" geometry={nodes['13-0180_Cylinder_Nut'].geometry} material={nodes['13-0180_Cylinder_Nut'].material} position={[-0.255, 3.303, 1.916]} rotation={[-1.564, 0, -0.043]} scale={0.001} />
        <mesh name="01-1121_Cam_Screws001" geometry={nodes['01-1121_Cam_Screws001'].geometry} material={nodes['01-1121_Cam_Screws001'].material} position={[-0.24, 3.277, 1.905]} rotation={[-Math.PI, -1.528, 3.135]} scale={0.001} />
        <mesh name="Standard_8800_(not_for_16,_28,_63,_66)" geometry={nodes['Standard_8800_(not_for_16,_28,_63,_66)'].geometry} material={materials['Material.017']} position={[0.058, -0.138, 0.334]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.025} />
        <mesh name="Chassis_Mounting_Screw" geometry={nodes.Chassis_Mounting_Screw.geometry} material={nodes.Chassis_Mounting_Screw.material} position={[-0.053, 3.128, 1.944]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.001} />
        <mesh name="Chassis_Mounting_Screw001" geometry={nodes.Chassis_Mounting_Screw001.geometry} material={nodes.Chassis_Mounting_Screw001.material} position={[-0.013, 3.128, 1.944]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.001} />
        <mesh name="Chassis_Mounting_Screw002" geometry={nodes.Chassis_Mounting_Screw002.geometry} material={nodes.Chassis_Mounting_Screw002.material} position={[-0.013, 2.959, 1.945]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.001} />
        <mesh name="Chassis_Mounting_Screw003" geometry={nodes.Chassis_Mounting_Screw003.geometry} material={nodes.Chassis_Mounting_Screw003.material} position={[-0.053, 2.959, 1.945]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.001} />
        <group name="01-4537_Hole_Plug" position={[-0.331, 2.838, 1.892]} rotation={[-Math.PI, 0, 0]} scale={0.001}>
          <mesh name="01-4537_Hole_Plug_1" geometry={nodes['01-4537_Hole_Plug_1'].geometry} material={materials['Material.014']} />
          <mesh name="01-4537_Hole_Plug_2" geometry={nodes['01-4537_Hole_Plug_2'].geometry} material={materials['Material.015']} />
          <mesh name="01-4537_Hole_Plug_3" geometry={nodes['01-4537_Hole_Plug_3'].geometry} material={materials['Material.016']} />
          <mesh name="01-4537_Hole_Plug_4" geometry={nodes['01-4537_Hole_Plug_4'].geometry} material={materials['0.752941_0.752941_0.752941_0.000000_0.013']} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.020']} position={[0.196, 0.067, 0.313]} scale={[0.068, 3.569, 0.167]} />
        <mesh name="01-3622_Strike_Screw001" geometry={nodes['01-3622_Strike_Screw001'].geometry} material={nodes['01-3622_Strike_Screw001'].material} position={[0.165, 2.778, 1.499]} scale={0.001} />
        <mesh name="01-1141_chassis_to_rail_screw" geometry={nodes['01-1141_chassis_to_rail_screw'].geometry} material={nodes['01-1141_chassis_to_rail_screw'].material} position={[0.056, 2.854, 1.884]} scale={0.001} />
        <mesh name="01-1141_chassis_to_rail_screw001" geometry={nodes['01-1141_chassis_to_rail_screw001'].geometry} material={nodes['01-1141_chassis_to_rail_screw001'].material} position={[0.062, 2.812, 1.884]} rotation={[0, 0, Math.PI]} scale={0.001} />
        <mesh name="01-0011_Lock_Washer001" geometry={nodes['01-0011_Lock_Washer001'].geometry} material={nodes['01-0011_Lock_Washer001'].material} position={[0.175, 2.868, 1.806]} rotation={[0, 0, Math.PI / 2]} scale={0.001} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.022']} position={[-0.761, 0.046, 0.313]} scale={[0.068, 3.613, 0.167]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.021']} position={[-0.286, 1.127, 0.313]} rotation={[0, 0, Math.PI / 2]} scale={[0.089, 1.57, 0.167]} />
      </group>
    </group>
  )
}

useGLTF.preload('/FullDoorAssembly.glb')
